### PR TITLE
Update picy.sh

### PR DESCRIPTION
**Pull request by Walkman100**
spelling fix

[Review on Reviewable](https://reviewable.io/reviews/deavmi/picy/33)

### CODE REVIEW

**Comment by Walkman100** [comment]
Also on L167, `echo echoing`, should I change that?

**Comment by deavmi** [comment]
@Walkman100 No

**Comment by Walkman100** [comment]
@deavmi Why not (telegram comments FTW)

**Comment by deavmi** [comment]
@Walkman100 Because I'm the OP here

**Comment by deavmi** [comment]
@deavmi Thanks. I have merged the pull request. :)

**Comment by deavmi** [comment]
@deavmi Telegram makes this so easy. :)

**Comment by deavmi** [comment]
@deavmi "Also on L167, echo echoing, should I change that?" Yeah. Change it to echo'ing

**Comment by Walkman100** [comment]
I meant just remove the first echo: 
>#Send stdout generated by <del>echo</del> echoing all the contents of the variable [...]

**Pull request merged**
